require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods: [insert_all, update_all, delete_all]

Style/ClassAndModuleChildren:
  Enabled: False

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
