version: '3'

services:
  db:
    image: postgres:14
    container_name: app_db
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    image: app/web:latest
    container_name: app_web
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/tmp
    ports:
      - 8080:8080
    environment:
      CREATE_DB_ON_INIT: 'true'
