default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'app_development' %>

test:
  <<: *default
  database: app_test
